export const plans = [
  {
    id: 'basico',
    name: 'Básico',
    tagline: 'Para operadores pequeños',
    price: 'MX$499',
    priceNumeric: 499,
    priceUnit: '/mes',
    priceFootnote: 'Hasta 5 choferes',
    features: [
      'Viajes ilimitados',
      'WhatsApp para choferes',
      'Dashboard de aprobaciones',
      'Evidencia guardada 6 meses',
      'Soporte por correo',
    ],
    recommended: false,
  },
  {
    id: 'pyme',
    name: 'PyMe',
    tagline: 'Para flotillas en crecimiento',
    price: 'MX$1,299',
    priceNumeric: 1299,
    priceUnit: '/mes',
    priceFootnote: 'Hasta 15 choferes',
    features: [
      'Básico+',
      'Reportes exportables (CSV/Excel)',
      'Evidencia guardada 12 meses',
      'Filtros avanzados por chofer/cliente/ruta',
      'Soporte prioritario por WhatsApp',
    ],
    recommended: true,
  },
  {
    id: 'empresa',
    name: 'Empresa',
    tagline: 'Para flotillas grandes',
    price: 'Cotizar',
    priceNumeric: null,
    priceUnit: null,
    priceFootnote: '16+ choferes',
    features: [
      'PyMe+',
      'SLA y onboarding dedicado',
      'Integraciones (ERP/contabilidad)',
      'Retención de evidencia custom',
      'Gerente de cuenta asignado',
    ],
    recommended: false,
  },
]
